#Defaults
CONTENT_TYPE: "application/json"
BASE_URL: "https://api.paystack.co"
AUTHORIZATION: "Bearer ${paystack-client.secret-key}"

#TODO: How do I declare header once and re-use, to avoid repetition, like in my case below:
http:
  clients:

    plan-client:
      url: "${BASE_URL}/plan"
      headers:
        Content-Type: ${CONTENT_TYPE}
        Authorization: ${AUTHORIZATION}

    apple-pay-client:
      url: "${BASE_URL}/apple-pay"
      headers:
        Content-Type: ${CONTENT_TYPE}
        Authorization: ${AUTHORIZATION}

    transaction-client:
      url: "${BASE_URL}/transaction"
      headers:
        Content-Type: ${CONTENT_TYPE}
        Authorization: ${AUTHORIZATION}

    product-client:
      url: "${BASE_URL}/product"
      headers:
        Content-Type: ${CONTENT_TYPE}
        Authorization: ${AUTHORIZATION}