name: PaystackJavaClient Maven CI

on:
  repository_dispatch:
    types: [execute-publish]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Publish package
        run: mvn -B deploy -pl paystack-clients
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}